#############################################
# Input files to drive the pipeline
#############################################

# NOTES:
# .gz files are accepted
# all input sequences are convered to upper case
# line width for FASTA format default to 60

# provide path to genome file
# - It is recommended that fasta header be shorter than 40 characters otherwise RepeatModeler might error
# file will be renamed to 'genome.fa'
fasta: /path/to/genome.fa

# Run below command to identify the species options to provide
# Also, check the NCBI taxonomy to identify the correct species option - https://www.ncbi.nlm.nih.gov/taxonomy
# perl /tgac/software/testing/repeatmodeller/1.0.10/src/RepeatMasker/util/queryRepeatDatabase.pl -tree | les
# For example:
# species: Insecta -- for Bombus vestalis, the vestal cuckoo bumblebee
species: None

# Enable this option to generate RED repeats
run_red_repeats: False

# Close reference protein CDS fasta to mask the RepeatModeler fasta
# file will be renamed to 'close_reference.cds.fa'
close_reference : /path/to/close/close_reference.cds.fa

# organellar chloroplast|mitrochondrial nucleotide fasta to mask the RepeatModeler 'unknown|other' fasta
# file will be renamed to 'organellar.fa'
organellar_fasta: /path/to/organellar.fa

# output folder name, NOT path
output: ./output

# output logs will be written to "logs" directory inside output folder
logs: ./output/logs
#####
# END of input parameters
#####


#######################
# source required tools and provide parameters
# NOTE: below tools are required for the snakemake pipeline
#######################
source:
  repeatmodeler: "source repeatmodeler-1.0.11_CBG"
  repeatmasker: "source repeatmodeler-1.0.11_CBG"
  seqkit: "source seqkit-2.1.0_CBG"
  red: "source red-22052015_CBG"
  transposonpsi: "source transposonPSI-08222010"
  blast: "source blast-2.6.0"
  bedtools: "source bedtools-2.25.0"

#####
# END of source tools and parameters
#####


#############################################
# Job and JIRA configurations
#############################################
# DO NOT CHANGE THIS - IF WE DO THEN THE RED REPEATS AND THE REST OF THE PIPELINE NEEDS CAREFUL REVIEW
prefix:
  index_name: "genome.fa"
  close_reference_name: "close_reference.cds.fa"
  organellar_name: "organellar.fa"
chunks:
  transposonpsi: 500
params:
  time: "/usr/bin/time -v "
  du: "/usr/bin/time -v du -sch "
jira:
  # jira_id : "PPBFX-611" # An example
  jira_id : ""
  site: "http://jira-uat.earlham.ac.uk"
  username: "tgacpap"
  password_file: "/ei/cb/common/.jira_pwd"
notify_jira: False
#############################################
# END of Job and JIRA configurations
#############################################
